# Generated by Django 4.2.1 on 2023-05-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment_count",
            field=models.IntegerField(default=0, verbose_name="댓글 수"),
        ),
        migrations.AddField(
            model_name="post",
            name="like_count",
            field=models.IntegerField(default=0, verbose_name="좋아요 수"),
        ),
    ]
