# Generated by Django 4.1.7 on 2023-05-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_writer_alter_post_date_alter_post_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
        ),
    ]
