# Generated by Django 4.2.1 on 2023-05-16 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_comment_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="date",
            new_name="created_at",
        ),
    ]
