spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #/<IP>:<PORT>/<DB NAME>?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    favicon:
      requestMapping=false

logging:
  level:
    org.hibernate.SQL: DEBUG
server:
  port: 8080