spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mutsa?serverTimezone=Asia/Seoul
    username: root
    password: 1Dpsrkdn!

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace